# Use postgres/example user/password credentials
#version: '3.1'

services:

  db_movies:
    image: movie:db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql
      - ./docker-entrypoint-initdb.d/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5440:5440
